<a href="https://colab.research.google.com/github/Ghilmanzufar/Tugas_Pengatar_Sains_Data_Kelompok-8/blob/main/Pengenalan%20Array%20dengan%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TUGAS
## Pengenalan Array dengan Numpy

Kelompok :

1.GHILMAN ZUFAR

2.MUHAMMAD DZULFIKAR

3.DAVIN APRILLIO SIANTURI

4.MUHAMMAD IMAM FIRDAUS

5.REZKY AGYA KINANTI




In [ ]:
import numpy as np

# Membuat matriks dengan tipe data integer 64
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks
print("arr:")
print(arr)

# Mencetak shape dari matriks
print("\nShape arr:")
print(arr.shape)

# Mencetak tipe data dari matriks
print("\nTipe data arr:")
print(arr.dtype)

arr:
[[1 2 3]
 [5 6 7]]

Shape arr:
(2, 3)

Tipe data arr:
int64


In [ ]:
import numpy as np

# Membuat matriks random dengan shape 2x3 dan tipe data integer 64
arr_rdm = np.random.randint(low=-9223372036854775808, high=9223372036854775807,
                            size=(2, 3), dtype=np.int64)

# Mencetak matriks
print("arr_rdm:")
print(arr_rdm)

# Mencetak shape dari matriks
print("\nShape arr_rdm:")
print(arr_rdm.shape)

# Mencetak tipe data dari matriks
print("\nTipe data arr_rdm:")
print(arr_rdm.dtype)


arr_rdm:
[[ 4620506784015747113  4847855129372195057 -4198557445623807349]
 [ 5933661799733492947 -5186876322483702349  7781089259501474656]]

Shape arr_rdm:
(2, 3)

Tipe data arr_rdm:
int64


# Aritmatika Dasar dengan Numpy

In [ ]:
import numpy as np

# Membuat matriks arr dan arr_rdm
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
arr_rdm = np.random.randint(low=-9223372036854775808, high=9223372036854775807,
                            size=(2, 3), dtype=np.int64)

# Operasi penjumlahan arr dan arr_rdm
sum_arr = np.add(arr, arr_rdm)
print("Hasil penjumlahan arr dan arr_rdm:")
print(sum_arr)

# Operasi pengurangan arr dan arr_rdm
sub_arr = np.subtract(arr, arr_rdm)
print("\nHasil pengurangan arr dan arr_rdm:")
print(sub_arr)

# Operasi perpangkatan dua arr_rdm
pow_arr_rdm = np.power(arr_rdm, 2)
print("\nHasil perpangkatan dua arr_rdm:")
print(pow_arr_rdm)

# Operasi perkalian elemen arr dan arr_rdm
mul_arr = np.multiply(arr, arr_rdm)
print("\nHasil perkalian elemen arr dan arr_rdm:")
print(mul_arr)

Hasil penjumlahan arr dan arr_rdm:
[[ 2265191323215447996 -8555656214454603792  6186750699353607686]
 [ 5905091661000371760  2025758465573077196  5201965038655541175]]

Hasil pengurangan arr dan arr_rdm:
[[-2265191323215447994  8555656214454603796 -6186750699353607680]
 [-5905091661000371750 -2025758465573077184 -5201965038655541161]]

Hasil perpangkatan dua arr_rdm:
[[  976123401306522265  -289621772507397820 -1232050134662097911]
 [-8530834908465005767 -2528921228932048604 -7763686444926363392]]

Hasil perkalian elemen arr dan arr_rdm:
[[ 2265191323215447995  1335431644800344028   113508024351271433]
 [-7368029842417244457 -6292193280271088476  -479732876830315056]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
# Nilai rata-rata arr
mean_arr = np.mean(arr)
print("\nNilai rata-rata matriks arr:")
print(mean_arr)


# Nilai rata-rata per baris matriks arr
mean_row_arr = np.mean(arr, axis=1)
print("\nNilai rata-rata per baris matriks arr:")
print(mean_row_arr)

# Total nilai seluruh elemen matriks arr
sum_total_arr = np.sum(arr)
print("\nTotal nilai seluruh elemen matriks arr:")
print(sum_total_arr)

# Nilai maksimal per kolom matriks arr
max_col_arr = np.max(arr, axis=0)
print("\nNilai maksimal per kolom matriks arr:")
print(max_col_arr)


Nilai rata-rata matriks arr:
4.0

Nilai rata-rata per baris matriks arr:
[2. 6.]

Total nilai seluruh elemen matriks arr:
24

Nilai maksimal per kolom matriks arr:
[5 6 7]


# Fitur pada Numpy

In [ ]:
import numpy as np

# Membuat array arrg dengan nilai range 1-20
arrg = np.arange(1, 21)
print("Array arrg:")
print(arrg)

# Mencetak nilai arrg index 5
print("\nNilai arrg index 5:")
print(arrg[5])

# Mencetak nilai arrg untuk 3 elemen dari terakhir
print("\nNilai arrg untuk 3 elemen dari terakhir:")
print(arrg[-3:])

# Mencetak nilai arrg 3 sampai 6
print("\nNilai arrg 3 sampai 6:")
print(arrg[3:7])  # Indeks di Python dimulai dari 0 dan slicing tidak termasuk batas akhir

Array arrg:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Nilai arrg index 5:
6

Nilai arrg untuk 3 elemen dari terakhir:
[18 19 20]

Nilai arrg 3 sampai 6:
[4 5 6 7]


In [ ]:
import numpy as np

# Membuat matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks arr
print("Matriks arr:")
print(arr)

# Mencetak slice matriks arr dengan output [[2, 3], [6, 7]]
print("\nSlice matriks arr [[2, 3], [6, 7]]:")
print(arr[:, 1:])

# Mencetak slice matriks arr dengan output [[3], [7]]
print("\nSlice matriks arr [[3], [7]]:")
print(arr[:, 2:])

Matriks arr:
[[1 2 3]
 [5 6 7]]

Slice matriks arr [[2, 3], [6, 7]]:
[[2 3]
 [6 7]]

Slice matriks arr [[3], [7]]:
[[3]
 [7]]


In [ ]:
import numpy as np

# Membuat matriks mtx_rdm ukuran 3x4 dengan tipe data integer, isi elemennya random
mtx_rdm = np.random.randint(low=-9223372036854775808, high=9223372036854775807,
                            size=(3, 4), dtype=np.int64)

# Mencetak shape mtx_rdm
print("Shape mtx_rdm:")
print(mtx_rdm.shape)

# Mengubah shape mtx_rdm menjadi satu dimensi
mtx_rdm = mtx_rdm.reshape(-1)
print("\nShape mtx_rdm setelah diubah menjadi satu dimensi:")
print(mtx_rdm.shape)

# Mengubah shape mtx_rdm menjadi 6x2
mtx_rdm = mtx_rdm.reshape(6, 2)
print("\nShape mtx_rdm setelah diubah menjadi 6x2:")
print(mtx_rdm.shape)


Shape mtx_rdm:
(3, 4)

Shape mtx_rdm setelah diubah menjadi satu dimensi:
(12,)

Shape mtx_rdm setelah diubah menjadi 6x2:
(6, 2)
